mediapark_advertisement:
    resource: "@MediaparkAdvertisementBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@MediaparkAdvertisementBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
